name = input("name :")
print(name)
age = int(input("age :"))
print(age)
print("your name", name, "your age", age)
a,b = 2,1
print(a**b)
a = input("a .")
b = input("b .")
print(a,b)
#print(not True andFalse or True)
